### ISSUE TITLE
 Importing flask.ext.cors is deprecated, use flask_cors instead.

### ISSUE THREAD

**Issue by NbR404** [xtr4nge/FruityC2#1]
./FruityC2.py:49: ExtDeprecationWarning: Importing flask.ext.cors is deprecated, use flask_cors instead.
  from flask.ext.cors import CORS

**Comment by xtr4nge** [comment]
Hi ravemandot,
Welcome to FruityC2 project and thanks for opening the issues ;)

For now using "flask.ext.cors" is only a warning and should work well, but I will add the new format on the next release, thanks for that.

In the meantime, you can replace `from flask.ext.cors import CORS` for `from flask_cors import CORS` on FruityC2.py

regards,

**Comment by NbR404** [comment]
Thank you!
