### ISSUE TITLE
default user?

### ISSUE THREAD

**Issue by 1N3** [xtr4nge/FruityC2#3]
Is there a default user to use when first logging into the C2 server? I tried admin/guest but can't connect to my local C2 server.

**Comment by xtr4nge** [comment]
Hi 1N3,
There is not user/pass/token implemented at the moment. (It will be implemented soon)
The access control is performed by source, you need to allow your source IP, check the Tutorial, you will find the step-by-step there ;)
https://github.com/xtr4nge/FruityC2-Client/wiki/FruityC2-101

The "user" field is just descriptive and do not have any impact on the access to the C2, so if multiple users are connected to the C2, they can identify each other on the chat/logs.

let me know if you solved the problem ;)
regards,

**Comment by 1N3** [comment]
thanks! I was able to get it working 👍

**Comment by xtr4nge** [comment]
Cool, no prob at all ;)

regards,
