### ISSUE TITLE
FruityC2 Server not reachable Error: Host or Port

### ISSUE THREAD

**Issue by n1ete** [xtr4nge/FruityC2#5]
first i wanna say thank your for your time developing this and made it availble to the public.
cant wait to see this getting intergrated into fruitywifi :+1: 

like the title already suggests: i am not able to connect the client to the server
the server seems installed fine i added also another control IP and leave the default port for testing

then i cloned the clientfiles on same machine as the server is running and opend index.html in the browser and typed in the 127.0.0.1 as server, put the port 5000 and admin as user but i get only an  "Error: Host or Port" back....

so i had a look at the traceback file in the log folder and found some json related error...

`2018-07-17 04:16:05 
 Traceback (most recent call last):
  File "./FruityC2.py", line 135, in <module>
    gdata.credentials = json.load(data)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
 
2018-07-17 04:16:05 
 Traceback (most recent call last):
  File "./FruityC2.py", line 141, in <module>
    with open('data/credentials_spn.json') as data:
IOError: [Errno 2] No such file or directory: 'data/credentials_spn.json'
 
`

do i have to add the api token into the credentials
any help appreciated! :D

**Comment by xtr4nge** [comment]
Hi n1ete,
Sorry for the delay in my response. I missed this Issue message.
Looks like this error was generated because default JSON files were not checked/created before to be loaded and used. It should be solved now.

regards,
